# Pandas

In [1]:
import pandas as pd
import numpy as np
import random as r

In [2]:
dict = {
    "Name" : ["Rohan", "Rohit", "Deepak"],
    "Class" : ["A", "B", "C"],
    "Marks" : [50, 60, 70]
}

In [3]:
df = pd.DataFrame(dict)
df

     Name Class  Marks
0   Rohan     A     50
1   Rohit     B     60
2  Deepak     C     70

In [4]:
df.to_csv('pandas.csv')

In [5]:
df.to_csv("pandas.csv", index = False)

In [6]:
df.head(2)

    Name Class  Marks
0  Rohan     A     50
1  Rohit     B     60

In [7]:
df.tail(2)

     Name Class  Marks
1   Rohit     B     60
2  Deepak     C     70

In [8]:
df.describe()

       Marks
count    3.0
mean    60.0
std     10.0
min     50.0
25%     55.0
50%     60.0
75%     65.0
max     70.0

In [14]:
data = []
for i in range(50):
    data.append({
        "no": i+1,
        "Class": r.choice(range(1, 13)),
        "Marks": r.choice(range(0, 101)),
        "Age": r.choice(range(15, 21))
    })

In [15]:
df2 = pd.DataFrame(data)
df2

    no  Class  Marks  Age
0    1      6     63   17
1    2      3     84   19
2    3      1     81   16
3    4      6     47   19
4    5     10     72   18
5    6      8     64   20
6    7      3      0   18
7    8     11     42   20
8    9      4     51   16
9   10      4     30   15
10  11     10     97   17
11  12     11     21   18
12  13      7     60   16
13  14      7     48   16
14  15     12     60   20
15  16     11     40   20
16  17      3     68   15
17  18      8     76   16
18  19      2     96   18
19  20      2     21   17
20  21      5     27   15
21  22      7     29   17
22  23      8      5   19
23  24      1     28   16
24  25      9      4   20
25  26      8     58   19
26  27      4     70   19
27  28     12     13   16
28  29      8      1   15
29  30      8     73   16
30  31      7     50   16
31  32      7     88   17
32  33     11     81   17
33  34     10     75   18
34  35      1     35   20
35  36      9     88   19
36  37      4     27   18
37  38      8     53   20
38  39      5     41   19
39  40      5     73   19
40  41      7      1   16
41  42     11     22   16
42  43      9     88   17
43  44     10     60   19
44  45     12     63   20
45  46      7     83   19
46  47      1     16   19
47  48      7      5   15
48  49      4     61   20
49  50     11     23   19

In [16]:
df2.to_csv('pandas2.csv', index = False)

In [17]:
csv2 = pd.read_csv('pandas2.csv')
csv2

    no  Class  Marks  Age
0    1      6     63   17
1    2      3     84   19
2    3      1     81   16
3    4      6     47   19
4    5     10     72   18
5    6      8     64   20
6    7      3      0   18
7    8     11     42   20
8    9      4     51   16
9   10      4     30   15
10  11     10     97   17
11  12     11     21   18
12  13      7     60   16
13  14      7     48   16
14  15     12     60   20
15  16     11     40   20
16  17      3     68   15
17  18      8     76   16
18  19      2     96   18
19  20      2     21   17
20  21      5     27   15
21  22      7     29   17
22  23      8      5   19
23  24      1     28   16
24  25      9      4   20
25  26      8     58   19
26  27      4     70   19
27  28     12     13   16
28  29      8      1   15
29  30      8     73   16
30  31      7     50   16
31  32      7     88   17
32  33     11     81   17
33  34     10     75   18
34  35      1     35   20
35  36      9     88   19
36  37      4     27   18
37  38      8     53   20
38  39      5     41   19
39  40      5     73   19
40  41      7      1   16
41  42     11     22   16
42  43      9     88   17
43  44     10     60   19
44  45     12     63   20
45  46      7     83   19
46  47      1     16   19
47  48      7      5   15
48  49      4     61   20
49  50     11     23   19

In [18]:
csv2['no'][0] = 5
csv2

C:\Users\agraw\AppData\Local\Temp\ipykernel_15128\3514181185.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv2['no'][0] = 5

    no  Class  Marks  Age
0    5      6     63   17
1    2      3     84   19
2    3      1     81   16
3    4      6     47   19
4    5     10     72   18
5    6      8     64   20
6    7      3      0   18
7    8     11     42   20
8    9      4     51   16
9   10      4     30   15
10  11     10     97   17
11  12     11     21   18
12  13      7     60   16
13  14      7     48   16
14  15     12     60   20
15  16     11     40   20
16  17      3     68   15
17  18      8     76   16
18  19      2     96   18
19  20      2     21   17
20  21      5     27   15
21  22      7     29   17
22  23      8      5   19
23  24      1     28   16
24  25      9      4   20
25  26      8     58   19
26  27      4     70   19
27  28     12     13   16
28  29      8      1   15
29  30      8     73   16
30  31      7     50   16
31  32      7     88   17
32  33     11     81   17
33  34     10     75   18
34  35      1     35   20
35  36      9     88   19
36  37      4     27   18
37  38      8     53   20
38  39      5     41   19
39  40      5     73   19
40  41      7      1   16
41  42     11     22   16
42  43      9     88   17
43  44     10     60   19
44  45     12     63   20
45  46      7     83   19
46  47      1     16   19
47  48      7      5   15
48  49      4     61   20
49  50     11     23   19

In [19]:
csv2

    no  Class  Marks  Age
0    5      6     63   17
1    2      3     84   19
2    3      1     81   16
3    4      6     47   19
4    5     10     72   18
5    6      8     64   20
6    7      3      0   18
7    8     11     42   20
8    9      4     51   16
9   10      4     30   15
10  11     10     97   17
11  12     11     21   18
12  13      7     60   16
13  14      7     48   16
14  15     12     60   20
15  16     11     40   20
16  17      3     68   15
17  18      8     76   16
18  19      2     96   18
19  20      2     21   17
20  21      5     27   15
21  22      7     29   17
22  23      8      5   19
23  24      1     28   16
24  25      9      4   20
25  26      8     58   19
26  27      4     70   19
27  28     12     13   16
28  29      8      1   15
29  30      8     73   16
30  31      7     50   16
31  32      7     88   17
32  33     11     81   17
33  34     10     75   18
34  35      1     35   20
35  36      9     88   19
36  37      4     27   18
37  38      8     53   20
38  39      5     41   19
39  40      5     73   19
40  41      7      1   16
41  42     11     22   16
42  43      9     88   17
43  44     10     60   19
44  45     12     63   20
45  46      7     83   19
46  47      1     16   19
47  48      7      5   15
48  49      4     61   20
49  50     11     23   19

In [20]:
csv2.index = ['A', 'B', 'C']
csv2

ValueError: Length mismatch: Expected axis has 50 elements, new values have 3 elements

In [ ]:
df2

In [ ]:
df2.index = ['A', 'B', 'C']
df2

In [21]:
series = pd.Series(np.random.rand(20))
series

0     0.305076
1     0.196907
2     0.236904
3     0.813734
4     0.540169
5     0.387810
6     0.830213
7     0.386476
8     0.305547
9     0.154982
10    0.276512
11    0.785381
12    0.951471
13    0.452252
14    0.107861
15    0.919926
16    0.935781
17    0.094453
18    0.220736
19    0.625610
dtype: float64

In [22]:
type(series)

pandas.core.series.Series

In [23]:
dataframe = pd.DataFrame(np.random.rand(20, 5))
dataframe

           0         1         2         3         4
0   0.736812  0.866410  0.633314  0.921608  0.403168
1   0.649928  0.483243  0.416176  0.517819  0.463846
2   0.022610  0.137141  0.264422  0.622196  0.030399
3   0.904971  0.889258  0.849759  0.564024  0.766791
4   0.137141  0.489680  0.180091  0.850871  0.366889
5   0.038385  0.272515  0.172284  0.292856  0.899346
6   0.867648  0.746777  0.578211  0.646651  0.085185
7   0.004462  0.499327  0.083581  0.155246  0.795134
8   0.426619  0.792518  0.978601  0.649546  0.672486
9   0.066689  0.648673  0.459889  0.055138  0.777906
10  0.356589  0.365601  0.312623  0.791403  0.205783
11  0.509562  0.397880  0.262201  0.833664  0.841784
12  0.657430  0.420585  0.168314  0.023230  0.639920
13  0.472695  0.734627  0.457485  0.460383  0.573717
14  0.138211  0.586431  0.409388  0.429342  0.890199
15  0.272969  0.334367  0.288514  0.487924  0.652267
16  0.586867  0.976377  0.404629  0.331691  0.516278
17  0.861668  0.046632  0.016019  0.155728  0.066160
18  0.355352  0.240677  0.941475  0.550453  0.969635
19  0.453369  0.107226  0.886625  0.675945  0.241380

In [24]:
dataframe = pd.DataFrame(np.random.rand(20, 5), index = np.arange(20))
dataframe

           0         1         2         3         4
0   0.338749  0.002833  0.423172  0.850110  0.995768
1   0.273334  0.432340  0.274471  0.337137  0.440924
2   0.993018  0.587280  0.522808  0.149792  0.263183
3   0.051474  0.703302  0.568315  0.895379  0.284374
4   0.615674  0.057095  0.758281  0.943273  0.181848
5   0.178798  0.345024  0.770684  0.226855  0.660369
6   0.445352  0.765403  0.601946  0.452101  0.111317
7   0.486563  0.571137  0.418960  0.100360  0.458633
8   0.412756  0.855383  0.163038  0.203454  0.644799
9   0.415406  0.831477  0.688159  0.563205  0.748254
10  0.451872  0.245415  0.170845  0.925058  0.255183
11  0.456768  0.428811  0.918863  0.277021  0.054068
12  0.550786  0.846438  0.260207  0.081523  0.053721
13  0.330346  0.333602  0.071272  0.492796  0.632976
14  0.292409  0.369675  0.084838  0.448466  0.478644
15  0.931772  0.500907  0.044468  0.763046  0.638590
16  0.554682  0.192303  0.843992  0.291996  0.134756
17  0.508473  0.855648  0.746864  0.153374  0.163505
18  0.907644  0.688442  0.818980  0.622374  0.858731
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [25]:
type(dataframe)

pandas.core.frame.DataFrame

In [26]:
dataframe.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [27]:
dataframe[0][0] = "A"
dataframe.dtypes

C:\Users\agraw\AppData\Local\Temp\ipykernel_15128\3754049245.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[0][0] = "A"
C:\Users\agraw\AppData\Local\Temp\ipykernel_15128\3754049245.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'A' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataframe[0][0] = "A"

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [28]:
dataframe.head(5)

          0         1         2         3         4
0         A  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924
2  0.993018  0.587280  0.522808  0.149792  0.263183
3  0.051474  0.703302  0.568315  0.895379  0.284374
4  0.615674  0.057095  0.758281  0.943273  0.181848

In [29]:
dataframe.index

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype='int64')

In [30]:
dataframe.columns

RangeIndex(start=0, stop=5, step=1)

In [31]:
dataframe.to_numpy()

array([['A', 0.0028328360719173107, 0.4231718760286327,
        0.8501104389419347, 0.995767729273505],
       [0.2733338138730026, 0.4323397125390027, 0.2744708418136701,
        0.33713731100721067, 0.44092446169083854],
       [0.9930180811015281, 0.5872802123376347, 0.5228080116453175,
        0.1497915835750281, 0.2631825727381636],
       [0.0514743412229397, 0.703301973861852, 0.568315278108562,
        0.8953793597981027, 0.2843739029196628],
       [0.6156735441208905, 0.05709538335487718, 0.7582811107346586,
        0.9432733044465725, 0.18184847654313607],
       [0.17879812674730777, 0.3450237398531243, 0.7706838344848299,
        0.22685541804753984, 0.6603688804570618],
       [0.44535219419799, 0.7654030436002235, 0.6019455284620598,
        0.45210081177375705, 0.11131704500942297],
       [0.48656259998149565, 0.5711367817356539, 0.4189601496141273,
        0.10035957828734232, 0.45863253953439],
       [0.41275576834866257, 0.8553830252398186, 0.16303807015302163,
        0.20345379929001728, 0.6447986701572457],
       [0.41540575191596063, 0.8314774453148255, 0.6881589921263,
        0.5632051544899837, 0.7482539174897745],
       [0.45187152054056134, 0.24541508524417055, 0.17084502391763212,
        0.9250579473479089, 0.2551827835057223],
       [0.4567676594386597, 0.4288109866303371, 0.9188632315907078,
        0.27702081812528523, 0.054068203453486285],
       [0.5507864872333267, 0.8464384286413105, 0.26020696951150646,
        0.08152269854985905, 0.05372106894997053],
       [0.3303464686777041, 0.33360194563928525, 0.07127239921906403,
        0.4927961707768411, 0.6329755163977162],
       [0.29240927744300294, 0.36967519811338245, 0.08483785264878618,
        0.4484662230798463, 0.4786440679202113],
       [0.9317717572139876, 0.5009069002125458, 0.04446830304768723,
        0.7630460334376885, 0.6385898858206591],
       [0.5546822950112072, 0.19230336586624286, 0.8439924104119815,
        0.2919958475152926, 0.13475583485683063],
       [0.5084726243777414, 0.8556480098788594, 0.7468642294155208,
        0.1533737123884904, 0.1635046138824866],
       [0.9076441238906168, 0.6884417250793325, 0.8189801036029086,
        0.6223738139385865, 0.8587309041771508],
       [0.13751191578176192, 0.48031124520728896, 0.038303867085591525,
        0.9540811570881661, 0.04568817856663432]], dtype=object)

In [32]:
dataframe[0][0] = 0.3
dataframe.head(2)

          0         1         2         3         4
0       0.3  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924

In [33]:
dataframe.to_numpy()

array([[0.3, 0.0028328360719173107, 0.4231718760286327,
        0.8501104389419347, 0.995767729273505],
       [0.2733338138730026, 0.4323397125390027, 0.2744708418136701,
        0.33713731100721067, 0.44092446169083854],
       [0.9930180811015281, 0.5872802123376347, 0.5228080116453175,
        0.1497915835750281, 0.2631825727381636],
       [0.0514743412229397, 0.703301973861852, 0.568315278108562,
        0.8953793597981027, 0.2843739029196628],
       [0.6156735441208905, 0.05709538335487718, 0.7582811107346586,
        0.9432733044465725, 0.18184847654313607],
       [0.17879812674730777, 0.3450237398531243, 0.7706838344848299,
        0.22685541804753984, 0.6603688804570618],
       [0.44535219419799, 0.7654030436002235, 0.6019455284620598,
        0.45210081177375705, 0.11131704500942297],
       [0.48656259998149565, 0.5711367817356539, 0.4189601496141273,
        0.10035957828734232, 0.45863253953439],
       [0.41275576834866257, 0.8553830252398186, 0.16303807015302163,
        0.20345379929001728, 0.6447986701572457],
       [0.41540575191596063, 0.8314774453148255, 0.6881589921263,
        0.5632051544899837, 0.7482539174897745],
       [0.45187152054056134, 0.24541508524417055, 0.17084502391763212,
        0.9250579473479089, 0.2551827835057223],
       [0.4567676594386597, 0.4288109866303371, 0.9188632315907078,
        0.27702081812528523, 0.054068203453486285],
       [0.5507864872333267, 0.8464384286413105, 0.26020696951150646,
        0.08152269854985905, 0.05372106894997053],
       [0.3303464686777041, 0.33360194563928525, 0.07127239921906403,
        0.4927961707768411, 0.6329755163977162],
       [0.29240927744300294, 0.36967519811338245, 0.08483785264878618,
        0.4484662230798463, 0.4786440679202113],
       [0.9317717572139876, 0.5009069002125458, 0.04446830304768723,
        0.7630460334376885, 0.6385898858206591],
       [0.5546822950112072, 0.19230336586624286, 0.8439924104119815,
        0.2919958475152926, 0.13475583485683063],
       [0.5084726243777414, 0.8556480098788594, 0.7468642294155208,
        0.1533737123884904, 0.1635046138824866],
       [0.9076441238906168, 0.6884417250793325, 0.8189801036029086,
        0.6223738139385865, 0.8587309041771508],
       [0.13751191578176192, 0.48031124520728896, 0.038303867085591525,
        0.9540811570881661, 0.04568817856663432]], dtype=object)

In [34]:
dataframe.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.3,0.273334,0.993018,0.051474,0.615674,0.178798,0.445352,0.486563,0.412756,0.415406,0.451872,0.456768,0.550786,0.330346,0.292409,0.931772,0.554682,0.508473,0.907644,0.137512
1,0.002833,0.43234,0.58728,0.703302,0.057095,0.345024,0.765403,0.571137,0.855383,0.831477,0.245415,0.428811,0.846438,0.333602,0.369675,0.500907,0.192303,0.855648,0.688442,0.480311
2,0.423172,0.274471,0.522808,0.568315,0.758281,0.770684,0.601946,0.41896,0.163038,0.688159,0.170845,0.918863,0.260207,0.071272,0.084838,0.044468,0.843992,0.746864,0.81898,0.038304
3,0.85011,0.337137,0.149792,0.895379,0.943273,0.226855,0.452101,0.10036,0.203454,0.563205,0.925058,0.277021,0.081523,0.492796,0.448466,0.763046,0.291996,0.153374,0.622374,0.954081
4,0.995768,0.440924,0.263183,0.284374,0.181848,0.660369,0.111317,0.458633,0.644799,0.748254,0.255183,0.054068,0.053721,0.632976,0.478644,0.63859,0.134756,0.163505,0.858731,0.045688

In [35]:
dataframe.sort_index(axis = 0, ascending = False)

           0         1         2         3         4
19  0.137512  0.480311  0.038304  0.954081  0.045688
18  0.907644  0.688442  0.818980  0.622374  0.858731
17  0.508473  0.855648  0.746864  0.153374  0.163505
16  0.554682  0.192303  0.843992  0.291996  0.134756
15  0.931772  0.500907  0.044468  0.763046  0.638590
14  0.292409  0.369675  0.084838  0.448466  0.478644
13  0.330346  0.333602  0.071272  0.492796  0.632976
12  0.550786  0.846438  0.260207  0.081523  0.053721
11  0.456768  0.428811  0.918863  0.277021  0.054068
10  0.451872  0.245415  0.170845  0.925058  0.255183
9   0.415406  0.831477  0.688159  0.563205  0.748254
8   0.412756  0.855383  0.163038  0.203454  0.644799
7   0.486563  0.571137  0.418960  0.100360  0.458633
6   0.445352  0.765403  0.601946  0.452101  0.111317
5   0.178798  0.345024  0.770684  0.226855  0.660369
4   0.615674  0.057095  0.758281  0.943273  0.181848
3   0.051474  0.703302  0.568315  0.895379  0.284374
2   0.993018  0.587280  0.522808  0.149792  0.263183
1   0.273334  0.432340  0.274471  0.337137  0.440924
0        0.3  0.002833  0.423172  0.850110  0.995768

In [36]:
dataframe.sort_index(axis = 1, ascending = False)

           4         3         2         1         0
0   0.995768  0.850110  0.423172  0.002833       0.3
1   0.440924  0.337137  0.274471  0.432340  0.273334
2   0.263183  0.149792  0.522808  0.587280  0.993018
3   0.284374  0.895379  0.568315  0.703302  0.051474
4   0.181848  0.943273  0.758281  0.057095  0.615674
5   0.660369  0.226855  0.770684  0.345024  0.178798
6   0.111317  0.452101  0.601946  0.765403  0.445352
7   0.458633  0.100360  0.418960  0.571137  0.486563
8   0.644799  0.203454  0.163038  0.855383  0.412756
9   0.748254  0.563205  0.688159  0.831477  0.415406
10  0.255183  0.925058  0.170845  0.245415  0.451872
11  0.054068  0.277021  0.918863  0.428811  0.456768
12  0.053721  0.081523  0.260207  0.846438  0.550786
13  0.632976  0.492796  0.071272  0.333602  0.330346
14  0.478644  0.448466  0.084838  0.369675  0.292409
15  0.638590  0.763046  0.044468  0.500907  0.931772
16  0.134756  0.291996  0.843992  0.192303  0.554682
17  0.163505  0.153374  0.746864  0.855648  0.508473
18  0.858731  0.622374  0.818980  0.688442  0.907644
19  0.045688  0.954081  0.038304  0.480311  0.137512

In [37]:
dataframe

           0         1         2         3         4
0        0.3  0.002833  0.423172  0.850110  0.995768
1   0.273334  0.432340  0.274471  0.337137  0.440924
2   0.993018  0.587280  0.522808  0.149792  0.263183
3   0.051474  0.703302  0.568315  0.895379  0.284374
4   0.615674  0.057095  0.758281  0.943273  0.181848
5   0.178798  0.345024  0.770684  0.226855  0.660369
6   0.445352  0.765403  0.601946  0.452101  0.111317
7   0.486563  0.571137  0.418960  0.100360  0.458633
8   0.412756  0.855383  0.163038  0.203454  0.644799
9   0.415406  0.831477  0.688159  0.563205  0.748254
10  0.451872  0.245415  0.170845  0.925058  0.255183
11  0.456768  0.428811  0.918863  0.277021  0.054068
12  0.550786  0.846438  0.260207  0.081523  0.053721
13  0.330346  0.333602  0.071272  0.492796  0.632976
14  0.292409  0.369675  0.084838  0.448466  0.478644
15  0.931772  0.500907  0.044468  0.763046  0.638590
16  0.554682  0.192303  0.843992  0.291996  0.134756
17  0.508473  0.855648  0.746864  0.153374  0.163505
18  0.907644  0.688442  0.818980  0.622374  0.858731
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [38]:
dataframe[0]

0          0.3
1     0.273334
2     0.993018
3     0.051474
4     0.615674
5     0.178798
6     0.445352
7     0.486563
8     0.412756
9     0.415406
10    0.451872
11    0.456768
12    0.550786
13    0.330346
14    0.292409
15    0.931772
16    0.554682
17    0.508473
18    0.907644
19    0.137512
Name: 0, dtype: object

In [39]:
type(dataframe)

pandas.core.frame.DataFrame

In [40]:
dataframe1 = dataframe

In [41]:
dataframe1[0][0] = 0.4

In [42]:
dataframe1

           0         1         2         3         4
0        0.4  0.002833  0.423172  0.850110  0.995768
1   0.273334  0.432340  0.274471  0.337137  0.440924
2   0.993018  0.587280  0.522808  0.149792  0.263183
3   0.051474  0.703302  0.568315  0.895379  0.284374
4   0.615674  0.057095  0.758281  0.943273  0.181848
5   0.178798  0.345024  0.770684  0.226855  0.660369
6   0.445352  0.765403  0.601946  0.452101  0.111317
7   0.486563  0.571137  0.418960  0.100360  0.458633
8   0.412756  0.855383  0.163038  0.203454  0.644799
9   0.415406  0.831477  0.688159  0.563205  0.748254
10  0.451872  0.245415  0.170845  0.925058  0.255183
11  0.456768  0.428811  0.918863  0.277021  0.054068
12  0.550786  0.846438  0.260207  0.081523  0.053721
13  0.330346  0.333602  0.071272  0.492796  0.632976
14  0.292409  0.369675  0.084838  0.448466  0.478644
15  0.931772  0.500907  0.044468  0.763046  0.638590
16  0.554682  0.192303  0.843992  0.291996  0.134756
17  0.508473  0.855648  0.746864  0.153374  0.163505
18  0.907644  0.688442  0.818980  0.622374  0.858731
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [43]:
dataframe.head()

          0         1         2         3         4
0       0.4  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924
2  0.993018  0.587280  0.522808  0.149792  0.263183
3  0.051474  0.703302  0.568315  0.895379  0.284374
4  0.615674  0.057095  0.758281  0.943273  0.181848

In [44]:
dataframe2 = dataframe.copy()

In [45]:
dataframe2[0][0] = 0.5
dataframe2.head()

C:\Users\agraw\AppData\Local\Temp\ipykernel_15128\2690816210.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe2[0][0] = 0.5
C:\Users\agraw\AppData\Local\Temp\ipykernel_15128\2690816210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataframe2[0][0] = 0.5

          0         1         2         3         4
0       0.5  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924
2  0.993018  0.587280  0.522808  0.149792  0.263183
3  0.051474  0.703302  0.568315  0.895379  0.284374
4  0.615674  0.057095  0.758281  0.943273  0.181848

In [46]:
dataframe.head()

          0         1         2         3         4
0       0.4  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924
2  0.993018  0.587280  0.522808  0.149792  0.263183
3  0.051474  0.703302  0.568315  0.895379  0.284374
4  0.615674  0.057095  0.758281  0.943273  0.181848

In [47]:
dataframe.loc[0,0] = 0.6
dataframe.head()

          0         1         2         3         4
0       0.6  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924
2  0.993018  0.587280  0.522808  0.149792  0.263183
3  0.051474  0.703302  0.568315  0.895379  0.284374
4  0.615674  0.057095  0.758281  0.943273  0.181848

In [48]:
dataframe.loc[0,5] = 0.6
dataframe

           0         1         2         3         4    5
0        0.6  0.002833  0.423172  0.850110  0.995768  0.6
1   0.273334  0.432340  0.274471  0.337137  0.440924  NaN
2   0.993018  0.587280  0.522808  0.149792  0.263183  NaN
3   0.051474  0.703302  0.568315  0.895379  0.284374  NaN
4   0.615674  0.057095  0.758281  0.943273  0.181848  NaN
5   0.178798  0.345024  0.770684  0.226855  0.660369  NaN
6   0.445352  0.765403  0.601946  0.452101  0.111317  NaN
7   0.486563  0.571137  0.418960  0.100360  0.458633  NaN
8   0.412756  0.855383  0.163038  0.203454  0.644799  NaN
9   0.415406  0.831477  0.688159  0.563205  0.748254  NaN
10  0.451872  0.245415  0.170845  0.925058  0.255183  NaN
11  0.456768  0.428811  0.918863  0.277021  0.054068  NaN
12  0.550786  0.846438  0.260207  0.081523  0.053721  NaN
13  0.330346  0.333602  0.071272  0.492796  0.632976  NaN
14  0.292409  0.369675  0.084838  0.448466  0.478644  NaN
15  0.931772  0.500907  0.044468  0.763046  0.638590  NaN
16  0.554682  0.192303  0.843992  0.291996  0.134756  NaN
17  0.508473  0.855648  0.746864  0.153374  0.163505  NaN
18  0.907644  0.688442  0.818980  0.622374  0.858731  NaN
19  0.137512  0.480311  0.038304  0.954081  0.045688  NaN

In [49]:
dataframe.drop(5, axis = 1)

           0         1         2         3         4
0        0.6  0.002833  0.423172  0.850110  0.995768
1   0.273334  0.432340  0.274471  0.337137  0.440924
2   0.993018  0.587280  0.522808  0.149792  0.263183
3   0.051474  0.703302  0.568315  0.895379  0.284374
4   0.615674  0.057095  0.758281  0.943273  0.181848
5   0.178798  0.345024  0.770684  0.226855  0.660369
6   0.445352  0.765403  0.601946  0.452101  0.111317
7   0.486563  0.571137  0.418960  0.100360  0.458633
8   0.412756  0.855383  0.163038  0.203454  0.644799
9   0.415406  0.831477  0.688159  0.563205  0.748254
10  0.451872  0.245415  0.170845  0.925058  0.255183
11  0.456768  0.428811  0.918863  0.277021  0.054068
12  0.550786  0.846438  0.260207  0.081523  0.053721
13  0.330346  0.333602  0.071272  0.492796  0.632976
14  0.292409  0.369675  0.084838  0.448466  0.478644
15  0.931772  0.500907  0.044468  0.763046  0.638590
16  0.554682  0.192303  0.843992  0.291996  0.134756
17  0.508473  0.855648  0.746864  0.153374  0.163505
18  0.907644  0.688442  0.818980  0.622374  0.858731
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [50]:
dataframe

           0         1         2         3         4    5
0        0.6  0.002833  0.423172  0.850110  0.995768  0.6
1   0.273334  0.432340  0.274471  0.337137  0.440924  NaN
2   0.993018  0.587280  0.522808  0.149792  0.263183  NaN
3   0.051474  0.703302  0.568315  0.895379  0.284374  NaN
4   0.615674  0.057095  0.758281  0.943273  0.181848  NaN
5   0.178798  0.345024  0.770684  0.226855  0.660369  NaN
6   0.445352  0.765403  0.601946  0.452101  0.111317  NaN
7   0.486563  0.571137  0.418960  0.100360  0.458633  NaN
8   0.412756  0.855383  0.163038  0.203454  0.644799  NaN
9   0.415406  0.831477  0.688159  0.563205  0.748254  NaN
10  0.451872  0.245415  0.170845  0.925058  0.255183  NaN
11  0.456768  0.428811  0.918863  0.277021  0.054068  NaN
12  0.550786  0.846438  0.260207  0.081523  0.053721  NaN
13  0.330346  0.333602  0.071272  0.492796  0.632976  NaN
14  0.292409  0.369675  0.084838  0.448466  0.478644  NaN
15  0.931772  0.500907  0.044468  0.763046  0.638590  NaN
16  0.554682  0.192303  0.843992  0.291996  0.134756  NaN
17  0.508473  0.855648  0.746864  0.153374  0.163505  NaN
18  0.907644  0.688442  0.818980  0.622374  0.858731  NaN
19  0.137512  0.480311  0.038304  0.954081  0.045688  NaN

In [51]:
dataframe = dataframe.drop(5, axis = 1)
dataframe

           0         1         2         3         4
0        0.6  0.002833  0.423172  0.850110  0.995768
1   0.273334  0.432340  0.274471  0.337137  0.440924
2   0.993018  0.587280  0.522808  0.149792  0.263183
3   0.051474  0.703302  0.568315  0.895379  0.284374
4   0.615674  0.057095  0.758281  0.943273  0.181848
5   0.178798  0.345024  0.770684  0.226855  0.660369
6   0.445352  0.765403  0.601946  0.452101  0.111317
7   0.486563  0.571137  0.418960  0.100360  0.458633
8   0.412756  0.855383  0.163038  0.203454  0.644799
9   0.415406  0.831477  0.688159  0.563205  0.748254
10  0.451872  0.245415  0.170845  0.925058  0.255183
11  0.456768  0.428811  0.918863  0.277021  0.054068
12  0.550786  0.846438  0.260207  0.081523  0.053721
13  0.330346  0.333602  0.071272  0.492796  0.632976
14  0.292409  0.369675  0.084838  0.448466  0.478644
15  0.931772  0.500907  0.044468  0.763046  0.638590
16  0.554682  0.192303  0.843992  0.291996  0.134756
17  0.508473  0.855648  0.746864  0.153374  0.163505
18  0.907644  0.688442  0.818980  0.622374  0.858731
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [52]:
dataframe.loc[[0,1], [0,1]]

          0         1
0       0.6  0.002833
1  0.273334  0.432340

In [53]:
dataframe.loc[:, [0,1]]

           0         1
0        0.6  0.002833
1   0.273334  0.432340
2   0.993018  0.587280
3   0.051474  0.703302
4   0.615674  0.057095
5   0.178798  0.345024
6   0.445352  0.765403
7   0.486563  0.571137
8   0.412756  0.855383
9   0.415406  0.831477
10  0.451872  0.245415
11  0.456768  0.428811
12  0.550786  0.846438
13  0.330346  0.333602
14  0.292409  0.369675
15  0.931772  0.500907
16  0.554682  0.192303
17  0.508473  0.855648
18  0.907644  0.688442
19  0.137512  0.480311

In [54]:
dataframe.loc[[0,1], :]

          0         1         2         3         4
0       0.6  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924

In [55]:
dataframe.loc[dataframe[0]<0.2]

           0         1         2         3         4
3   0.051474  0.703302  0.568315  0.895379  0.284374
5   0.178798  0.345024  0.770684  0.226855  0.660369
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [56]:
dataframe.loc[(dataframe[0]<0.2) & (dataframe[4]<0.2)]

           0         1         2         3         4
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [57]:
dataframe.head()

          0         1         2         3         4
0       0.6  0.002833  0.423172  0.850110  0.995768
1  0.273334  0.432340  0.274471  0.337137  0.440924
2  0.993018  0.587280  0.522808  0.149792  0.263183
3  0.051474  0.703302  0.568315  0.895379  0.284374
4  0.615674  0.057095  0.758281  0.943273  0.181848

In [58]:
print(dataframe.iloc[0, 4])

0.995767729273505

In [59]:
dataframe.iloc[[0,1], [0,1]]

          0         1
0       0.6  0.002833
1  0.273334  0.432340

In [60]:
dataframe.drop([0], axis = 0, inplace = True)

In [61]:
dataframe

           0         1         2         3         4
1   0.273334  0.432340  0.274471  0.337137  0.440924
2   0.993018  0.587280  0.522808  0.149792  0.263183
3   0.051474  0.703302  0.568315  0.895379  0.284374
4   0.615674  0.057095  0.758281  0.943273  0.181848
5   0.178798  0.345024  0.770684  0.226855  0.660369
6   0.445352  0.765403  0.601946  0.452101  0.111317
7   0.486563  0.571137  0.418960  0.100360  0.458633
8   0.412756  0.855383  0.163038  0.203454  0.644799
9   0.415406  0.831477  0.688159  0.563205  0.748254
10  0.451872  0.245415  0.170845  0.925058  0.255183
11  0.456768  0.428811  0.918863  0.277021  0.054068
12  0.550786  0.846438  0.260207  0.081523  0.053721
13  0.330346  0.333602  0.071272  0.492796  0.632976
14  0.292409  0.369675  0.084838  0.448466  0.478644
15  0.931772  0.500907  0.044468  0.763046  0.638590
16  0.554682  0.192303  0.843992  0.291996  0.134756
17  0.508473  0.855648  0.746864  0.153374  0.163505
18  0.907644  0.688442  0.818980  0.622374  0.858731
19  0.137512  0.480311  0.038304  0.954081  0.045688

In [62]:
dataframe.drop([0], axis = 1, inplace = True)
dataframe

           1         2         3         4
1   0.432340  0.274471  0.337137  0.440924
2   0.587280  0.522808  0.149792  0.263183
3   0.703302  0.568315  0.895379  0.284374
4   0.057095  0.758281  0.943273  0.181848
5   0.345024  0.770684  0.226855  0.660369
6   0.765403  0.601946  0.452101  0.111317
7   0.571137  0.418960  0.100360  0.458633
8   0.855383  0.163038  0.203454  0.644799
9   0.831477  0.688159  0.563205  0.748254
10  0.245415  0.170845  0.925058  0.255183
11  0.428811  0.918863  0.277021  0.054068
12  0.846438  0.260207  0.081523  0.053721
13  0.333602  0.071272  0.492796  0.632976
14  0.369675  0.084838  0.448466  0.478644
15  0.500907  0.044468  0.763046  0.638590
16  0.192303  0.843992  0.291996  0.134756
17  0.855648  0.746864  0.153374  0.163505
18  0.688442  0.818980  0.622374  0.858731
19  0.480311  0.038304  0.954081  0.045688

In [63]:
dataframe.reset_index()

    index         1         2         3         4
0       1  0.432340  0.274471  0.337137  0.440924
1       2  0.587280  0.522808  0.149792  0.263183
2       3  0.703302  0.568315  0.895379  0.284374
3       4  0.057095  0.758281  0.943273  0.181848
4       5  0.345024  0.770684  0.226855  0.660369
5       6  0.765403  0.601946  0.452101  0.111317
6       7  0.571137  0.418960  0.100360  0.458633
7       8  0.855383  0.163038  0.203454  0.644799
8       9  0.831477  0.688159  0.563205  0.748254
9      10  0.245415  0.170845  0.925058  0.255183
10     11  0.428811  0.918863  0.277021  0.054068
11     12  0.846438  0.260207  0.081523  0.053721
12     13  0.333602  0.071272  0.492796  0.632976
13     14  0.369675  0.084838  0.448466  0.478644
14     15  0.500907  0.044468  0.763046  0.638590
15     16  0.192303  0.843992  0.291996  0.134756
16     17  0.855648  0.746864  0.153374  0.163505
17     18  0.688442  0.818980  0.622374  0.858731
18     19  0.480311  0.038304  0.954081  0.045688

In [64]:
dataframe.reset_index(drop = True, inplace = True)

In [65]:
dataframe

           1         2         3         4
0   0.432340  0.274471  0.337137  0.440924
1   0.587280  0.522808  0.149792  0.263183
2   0.703302  0.568315  0.895379  0.284374
3   0.057095  0.758281  0.943273  0.181848
4   0.345024  0.770684  0.226855  0.660369
5   0.765403  0.601946  0.452101  0.111317
6   0.571137  0.418960  0.100360  0.458633
7   0.855383  0.163038  0.203454  0.644799
8   0.831477  0.688159  0.563205  0.748254
9   0.245415  0.170845  0.925058  0.255183
10  0.428811  0.918863  0.277021  0.054068
11  0.846438  0.260207  0.081523  0.053721
12  0.333602  0.071272  0.492796  0.632976
13  0.369675  0.084838  0.448466  0.478644
14  0.500907  0.044468  0.763046  0.638590
15  0.192303  0.843992  0.291996  0.134756
16  0.855648  0.746864  0.153374  0.163505
17  0.688442  0.818980  0.622374  0.858731
18  0.480311  0.038304  0.954081  0.045688

In [66]:
dataframe[1].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
Name: 1, dtype: bool

In [67]:
dataframe.loc[[1]] = None

In [68]:
dataframe

           1         2         3         4
0   0.432340  0.274471  0.337137  0.440924
1        NaN       NaN       NaN       NaN
2   0.703302  0.568315  0.895379  0.284374
3   0.057095  0.758281  0.943273  0.181848
4   0.345024  0.770684  0.226855  0.660369
5   0.765403  0.601946  0.452101  0.111317
6   0.571137  0.418960  0.100360  0.458633
7   0.855383  0.163038  0.203454  0.644799
8   0.831477  0.688159  0.563205  0.748254
9   0.245415  0.170845  0.925058  0.255183
10  0.428811  0.918863  0.277021  0.054068
11  0.846438  0.260207  0.081523  0.053721
12  0.333602  0.071272  0.492796  0.632976
13  0.369675  0.084838  0.448466  0.478644
14  0.500907  0.044468  0.763046  0.638590
15  0.192303  0.843992  0.291996  0.134756
16  0.855648  0.746864  0.153374  0.163505
17  0.688442  0.818980  0.622374  0.858731
18  0.480311  0.038304  0.954081  0.045688

In [69]:
dataframe[1].isnull()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
Name: 1, dtype: bool